Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -30,6 +30,10 @@ jobs:
           sudo chmod +x /usr/local/bin/docker-compose
           docker-compose --version
 
+      - name: Create shared Docker network
+        run: |
+          docker network ls | grep kawa-shared-network || docker network create kawa-shared-network
+
       - name: Build Docker images
         run: |
           docker-compose build
@@ -39,25 +43,53 @@ jobs:
           docker-compose up -d
           sleep 60
 
+      # - name: Download wait-for-it script
+      #   run: wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
+    
+      # - name: Make wait-for-it executable
+      #   run: chmod +x wait-for-it.sh
+    
+      # - name: Wait for MySQL to be ready
+      #   run: ./wait-for-it.sh kawa-orders-db:3306 --timeout=120 --strict -- echo "MySQL is up"
+
       - name: Check Docker container logs
         run: |
-          docker-compose logs ${{ secrets.DOCKER_CONTAINER }}
+          docker-compose logs kawa-products-app
 
-      # - name: Verify Docker containers are running
+      - name: Verify Docker containers are running
+        run: |
+          docker ps
+
+          if ! docker ps | grep kawa-products-app; then
+            echo "Le conteneur n'est pas en cours d'exécution !"
+            exit 1
+          fi
+
+          if ! nc -zv localhost 8081; then
+            echo "Le port 8081 sur le conteneur n'est pas accessible !"
+            exit 1
+          fi
+        continue-on-error: true
+
+      # - name: Wait for the database to be ready
       #   run: |
-      #     docker ps
-
-      #     if ! docker ps | grep ${{ secrets.DOCKER_CONTAINER }}; then
-      #       echo "Le conteneur n'est pas en cours d'exécution !"
+      #     echo "Waiting for the database to be ready..."
+      #     for i in {1..10}; do
+      #       if nc -zv kawa-orders-db 3306; then  # Utiliser le nom du service Docker pour MySQL
+      #         echo "Database is ready!"
+      #         break
+      #       else
+      #         echo "Database is not ready yet... waiting"
+      #         sleep 10
+      #       fi
+      #     done
+      
+      #     # Échec si la base de données n'est toujours pas prête après 10 tentatives
+      #     if ! nc -zv kawa-orders-db 3306; then
+      #       echo "Database failed to start!"
       #       exit 1
       #     fi
 
-      #     if ! nc -zv localhost 8081; then
-      #       echo "Le port du conteneur n'est pas accessible !"
-      #       exit 1
-      #     fi
-      #   continue-on-error: true
-        
       - name: Run unit tests
         run: |
           # Installer les dépendances nécessaires pour exécuter les tests
@@ -149,3 +181,12 @@ jobs:
           curl -X POST -H "Content-Type: application/json" -d '{
             "content": "**Release Notes - API PRODUCT**\n\n**Commit N°**: '"${COMMIT_SHA}"'\n**Auteur du commit**: '"${COMMIT_AUTHOR}"'\n**Date du commit**: '"${COMMIT_DATE}"'\n**Heure du commit**: '"${COMMIT_TIME}"'\n**Description commit**: '"${COMMIT_MESSAGE}"'"
           }' "$DISCORD_WEBHOOK_URL_RELEASE"
+
+      # - name: Send Discord notification on release failure
+      #   if: failure() && steps.Send_Discord_release_notes.outcome == 'failure'  # Si l'étape d'envoi des release notes échoue
+      #   env:
+      #     DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
+      #   run: |
+      #     curl -X POST -H "Content-Type: application/json" -d '{
+      #       "content": "<@&ROLE_ID> **Release Notes Failure**\n\n**Repository:** ${{ github.repository }}\n**Commit SHA:** ${{ github.sha }}\n**Commit Message:** ${{ github.event.head_commit.message }}\n**Error:** Failed to send release notes"
+      #     }' "$DISCORD_WEBHOOK_URL"
