Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -15,40 +15,42 @@ jobs:
         run: |
           git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
           git config --global user.name "${{ secrets.GIT_USER_NAME }}"
-        continue-on-error: true
 
       - name: Checkout code
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
-        continue-on-error: true
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
-        continue-on-error: true
 
       - name: Install Docker Compose
         run: |
           sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
           docker-compose --version
-        continue-on-error: true
 
       - name: Build Docker images
         run: |
           docker-compose build
-        continue-on-error: true
 
       - name: Start Docker containers
         run: |
           docker-compose up -d
           sleep 60
-        continue-on-error: true
+
+      # - name: Download wait-for-it script
+      #   run: wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
+    
+      # - name: Make wait-for-it executable
+      #   run: chmod +x wait-for-it.sh
+    
+      # - name: Wait for MySQL to be ready
+      #   run: ./wait-for-it.sh kawa-orders-db:3306 --timeout=120 --strict -- echo "MySQL is up"
 
       - name: Check Docker container logs
         run: |
           docker-compose logs kawa-orders-app
-        continue-on-error: true
 
       - name: Verify Docker containers are running
         run: |
@@ -63,6 +65,35 @@ jobs:
             echo "Le port 8081 sur le conteneur kawa-orders-app n'est pas accessible !"
             exit 1
           fi
+        continue-on-error: true
+
+      # - name: Wait for the database to be ready
+      #   run: |
+      #     echo "Waiting for the database to be ready..."
+      #     for i in {1..10}; do
+      #       if nc -zv kawa-orders-db 3306; then  # Utiliser le nom du service Docker pour MySQL
+      #         echo "Database is ready!"
+      #         break
+      #       else
+      #         echo "Database is not ready yet... waiting"
+      #         sleep 10
+      #       fi
+      #     done
+      
+      #     # Échec si la base de données n'est toujours pas prête après 10 tentatives
+      #     if ! nc -zv kawa-orders-db 3306; then
+      #       echo "Database failed to start!"
+      #       exit 1
+      #     fi
+
+      - name: Run unit tests
+        run: |
+          # Installer les dépendances nécessaires pour exécuter les tests
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+
+          # Exécuter les tests avec unittest
+          python -m unittest discover -s tests -p "test_api.py"
         continue-on-error: true
 
         # Builder et pousser l'image Docker après la vérification des conteneurs
@@ -81,7 +112,6 @@ jobs:
         with:
           ref: release
           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-        continue-on-error: true
 
       - name: Update version in files on main
         if: success()
@@ -89,7 +119,6 @@ jobs:
           VERSION=$(date +"%Y.%m.%d")-$(git rev-parse --short HEAD)
           echo "Updating version to $VERSION"
           sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json
-        continue-on-error: true
 
       - name: Commit updated package.json on main
         if: success()
@@ -102,8 +131,6 @@ jobs:
           echo "Updating version to $VERSION"
           git commit -m "Update version to $VERSION [skip ci]"
           git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} main
-        continue-on-error: true
-
         
       - name: Checkout release branch with token
         if: success()
@@ -111,7 +138,6 @@ jobs:
         with:
           ref: release
           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-        continue-on-error: true
 
       - name: Merge main into release
         if: success()
@@ -121,7 +147,6 @@ jobs:
           git fetch origin main
           git checkout -B release origin/main
           git push --force https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} release
-        continue-on-error: true
 
       - name: Send Discord notification on failure
         if: failure()
